# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-17 21:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price_page', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('price_base', models.DecimalField(decimal_places=2, max_digits=6)),
                ('num_page_max', models.DecimalField(decimal_places=0, max_digits=2)),
                ('num_page_base', models.DecimalField(decimal_places=0, max_digits=2)),
                ('is_dynamic', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Sites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=6)),
                ('price_teir', models.CharField(max_length=255)),
                ('url', models.URLField(max_length=255)),
            ],
        ),
    ]
