# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-18 15:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamics', '0003_site_date_made'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('creater', models.CharField(max_length=125)),
            ],
        ),
        migrations.AddField(
            model_name='price',
            name='note',
            field=models.TextField(default='Hello'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='site',
            name='note',
            field=models.TextField(default='Hello'),
            preserve_default=False,
        ),
    ]
